### ISSUE TITLE
Mpv scripts are not working

### ISSUE THREAD

**Issue by random29** [FreeTubeApp/FreeTube#1667]
**Behavior of the program**
So, I use script mpv-sponsorblock https://github.com/po5/mpv_sponsorblock script.
Freetube ignores it. In console I just write mpv *videoUrl* and it works

**To Reproduce**
1. Go to https://github.com/po5/mpv_sponsorblock
2. Use script
3. Not working

**Environment Information (please complete the following information):**
 - OS: manjaro
 - OS Version: last
 - FreeTube version: last Developer version compiled hour ago
 - Installation Method (If applicable): compiled by npm install, nom run build and pacman -U .pacman
 

**Additional context**
Thanks

**Comment by drcassar** [comment]
It may be related to the way FreeTube sends the video link to mpv. The mpv sponsorblock plugin works with youtube links and with invidious links by extracting the ID using the `/watch?v=` string and querying the sponsorblock database with it. Perhaps FreeTube does not send the link with this ID to mpv? If this behaviour is by design (maybe to help FreeTube working with other players), could the devs add an option in the settings menu to just send directly the invidious link to mpv?

**Comment by suburbanbourbon** [comment]
I unfortunately have the same issue. Can we please get a fix?

**Comment by ajariel** [comment]
I made a quick dirty fix for myself by changing the mpv sponsorblock script itself. Turned out adding a single line of code did the trick:
```lua
local urls = {
	"ytdl://([%w-_]+).*", -- this line
        "https?://youtu%.be/([%w-_]+).*",
        "https?://w?w?w?%.?youtube%.com/v/([%w-_]+).*",
        "/watch.*[?&]v=([%w-_]+).*",
        "/embed/([%w-_]+).*"
}
```

**Comment by tharrisone** [comment]
Thank for the fix, and it works if I run mpv from the terminal but doesn't work if I use freetube and it runs mpv.. Gah :(

**Comment by rEnr3n** [comment]
Fixed in https://github.com/po5/mpv_sponsorblock/commit/7785c1477103f2fafabfd65fdcf28ef26e6d7f0d

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@rEnr3n so the script works now?

**Comment by rEnr3n** [comment]
Yes. Been working since.

**Comment by futureisfoss** [comment]
This issue is not fixed yet, I have the following mpv scripts which don't work when opening from FreeTube:

https://github.com/christoph-heinrich/mpv-quality-menu - allows me to change the youtube video quality inside mpv.
https://github.com/marzzzello/mpv_thumbnail_script - gives me thumbnail previews in the seekbar of mpv.

Unfortunately both of these mpv scripts don't work with `ytdl://` links (which is what FreeTube passes to mpv when used as the external player), and I suspect there are many more mpv scripts out there that don't work like this. I suggest passing a normal https link like `https://www.youtube.com/watch?v=dQw4w9WgXcQ` to mpv instead of `ytdl://dQw4w9WgXcQ`, or at least provide an option to toggle this please.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> we have no need to open it via the ytdl protocol to begin with

> we don't use any special features related to it (such as `ytsearch:`, `ytsearchdate:`, etc)
just pass the regular URL, it will save us a headache since we can't control what other projects/scripts are supporting

Retrieved from internal discussion

**Comment by futureisfoss** [comment]
Exactly, passing a regular URL will surely be more compatible with other mpv scripts. So if there is no need to use the `ytdl://` links then its better to remove that and use normal `https://` links instead.
