### ISSUE TITLE
[Bug]: Network download and buffering is significantly slower compared to browser

### ISSUE THREAD

**Issue by RevAngel7** [FreeTubeApp/FreeTube#3457]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Watching videos on FreeTube on 1080p often runs into buffer-underruns. Watching the same videos on browser there is no such problem. 

This can confirmed with any video that buffer-underruns on FreeTube - youtube on browser is not running into the same issue.

Tested on local API. Ubuntu .deb version v0.18.0-nightly-2844 Beta on ubuntu 22.04, kernel 6.2.12 mainline, mesa 23.1, all common codecs present. 100+mbit/s download speed. 12/16GB free RAM, fast SSD with enough free space.

### Expected Behavior

A "as fast as" download speed as viewing a video on my browser on youtube - with the local API of FreeTube. No buffer-underruns on 1080p (or higher).

### Issue Labels

content not loading, usability issue

### FreeTube Version

v0.18.0-nightly-2844 Beta

### Operating System Version

ubuntu 22.04 (LTS)

### Installation Method

.deb

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

None, issue was with previous versions as well.

### Additional Information

As I understood, the local API and FreeTube itself uses no special API key to access content from youtube. So why is it considerably slower than viewing content from youtube itself to a point where it buffer-underruns on 1080p on most videos in an environment where 100mbit/s and other hard- and software issues should not throttle in any way?

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by RevAngel7** [comment]
Definition to clarify: "1080p" means in my case 1080p60, 1080p30, 1080p23. Buffer underruns occur in all these 3 cases (even tho the contents bitrate varies).

**Comment by Joerg123** [comment]
I can confirm this behavior of the nightly builds, at least beginning with 2844, when i first tried out working with them 3 weeks ago because of an issue with the main 0.18.0 beta version because  of a change Youtube did then.
I did not put a comment because i'm just an user, not understanding much from the stuff, as you probable already guessed by my writing.
But perhapps i can give you further information, e.g. i'm using Windows 10 and i'm not aware of having any proxy set, i'm using local api.
![Unbenannt](https://user-images.githubusercontent.com/28968138/233799859-69018a34-01cc-4e32-9101-0078aebc143b.PNG)
Because for whatever reason, a few days after having problems with the 0.18.0 beta main version everything worked fine again, so i could fallback to 0.18.0 beta.
Actually i always had sometimes problems with buffering 1080p, but in this cases i had to pause for 30 seconds to get enough buffer for not having buffer underuns again during the playback of the video. But with the nightly build it takes a minute to buffer 5 seconds, thus totally unusable.

I think You have to ask me specific questions for getting the right informations, hope i can help...

**Comment by tytqnxt898** [comment]
The same issue happens to me on the latest build (not nightly). The way I fixed it was using a socks5 proxy which made the bandwidth on par with browsers.

To test this issue what I did was use 2 browser (chrome and firefox) and freetube + im using the same vpn ip for the tests. While checking the nerd stats of the same video on chrome and firefox I get 200k kpbs on th bandwidth. On freetube with the same ip and video I get 8k kbps which is drastically slower. 

The only fix I found was to use a socks5 proxy (which has the same ip as the vpn I'm using) and somehow it fixes it by going 200k kpbs on the bandwidth. 

On the nightly build sadly I cannot use this fix because the new method to use a proxy makes it worst than not having a proxy (100-200 kpbs) 50 times slower.

**Comment by RevAngel7** [comment]
Hello, and thank you all for your contributions.

To answer the questions:
No, I am not using a proxy (nor TOR). Neither over FreeTube nor the system.
No, I am not using my VPN with FreeTube. (Tested: using it does not change the situation.)

Thank you again for you trying to help!

**Comment by Growebis** [comment]
I though i was going crazy when some youtube videos would load perfectly fine in 1080p but others not.

**Comment by absidue** [comment]
Do you have any specific videos that this happens with? Every video I've tried so far has worked fine on my end in the nightly builds.

**Comment by Joerg123** [comment]
I tested it jesterday to comment, it didn't work: exremely slow buffering with the nightlies, but 0.18.0 beta worked. Today, it just works with every version, thus also nightlies. I don't konw...

**Comment by PikachuEXE** [comment]
Default Video Format and Allow AV1?
When I have VPN (home) I use legacy format but Dash one works fine for me when no VPN enabled (work).

**Comment by RevAngel7** [comment]
> Do you have any specific videos that this happens with? Every video I've tried so far has worked fine on my end in the nightly builds.

Nearly every video, but some work, some work for initial buffering and underrun some time in. On the non-nightly versions it worked sometimes to press CTRL-R to refresh the video page, sometimes this had to be repeated. I guessed at that time that servers were chosen at each loading of the video, and probably one was faster - but that was just my guess.


> Default Video Format and Allow AV1? When I have VPN (home) I use legacy format but Dash one works fine for me when no VPN enabled (work).

DASH video formats (default). As per default settings AV1 was not checked (on). But since I have the necessary codecs (libaom3, libdav1d5) installed I will test it again with AV1 checked (on) and report the results later.

By the way, I had these issues with the non-nighty versions too - maybe not as significant as on the nighy version I am using now. But I had to change the version since the non-nighty stopped working for me entirely.

**Comment by RevAngel7** [comment]
Turning AV1 on did not improve the issue.

**Comment by Joerg123** [comment]
Hmm, today , again, it's not working with the nightlies, but v0.18.0 Beta is working.
For a moment i thought, turning of AV1 Dash fixes the problem, but this was just for two times checking the same video and switching vise versa. After the third time swithichg AV1 off it not worked anymore.

**Comment by RevAngel7** [comment]
Changing to #2878 and testing if that improves the issue.

**Comment by RevAngel7** [comment]
Pre-Buffering seems to work a bit better, but after that buffer-underruns occur as frequent as with the previous versions.

**Comment by absidue** [comment]
Going back and forth between old stuff and new stuff won't make a difference, it's clearly a YouTube change but as we haven't been able to reproduce the issue on our end, we can't investigate and try to solve it.

**Comment by RevAngel7** [comment]
Okay, I get that. Strangely this issue now seems sporadic and unpredictable as well. I watched 10 videos now from various world news channels, and 5 of them went fine, 5 of them underrun.

Should we keep this issue open to have an eye on user experiences? And would that help wit the investigation of the issue?

**Comment by RevAngel7** [comment]
Or:
Can I provide you with more information that would help with the investigation?

Maybe I can stay updated with the nighties and write a test update from time to time. And if some users find the same issue, they maybe can contribute information about it until the puzzle turns into a readable picture?

**Comment by absidue** [comment]
Would be very useful if someone found a way to consistently reproduce this e.g. specific videos or that it happens more frequently on specific channels. Definitely keeping it open, because it's clearly an issue that multiple people are having so it's not just an issue with someone's setup, we just can't do anything about it until we have a way to reproduce the problem.

**Comment by RevAngel7** [comment]
> Would be very useful if someone found a way to consistently reproduce this e.g. specific videos or that it happens more frequently on specific channels. Definitely keeping it open, because it's clearly an issue that multiple people are having so it's not just an issue with someone's setup, we just can't do anything about it until we have a way to reproduce the problem.

Okay, lets work with that. Reproducing an issue that is as sporadic as this one is a pain, especially if it works fine on the dev's side (I worked on communications equipment and software in a lab, testing and fixing issues that were sporadic as well, with multiple carrier changes included to complicate puzzles). Let's gather more information from users to this issues until we maybe can get a clearer picture of the causes. 

Thank you for your effort and clear response, @absidue

**Comment by Growebis** [comment]
I find that this channel seems to have buffering underruns on most of the videos, is this the same for anyone else?
https://www.youtube.com/channel/UCXoKg7Uvy4E7G3oW-Id5k1A

**Comment by absidue** [comment]
@Growebis @shaicoleman Are you both using the nightly builds? Tried both playing 3x and videos that channel on the nightlies but unfortunately I still can replicate it.

**Comment by shaicoleman** [comment]
@absidue , seems fixed on the nightly build

**Comment by RevAngel7** [comment]
It got better, but is still underrunning buffering on 50% of 10 videos I tested.
After some underruns the recovery went fine, then catching up better than on the initial buffering.

One video in particular went really bad. Buffer underruns every (visual) cache segmentation (the red/gray bar under the video ;-)  on 1x speed, 1080p from start to end of the video.

https://youtu.be/dm8wcJROo4c (Reuters - One dead, 23 wounded in Russian missile strike - 2023-04-27)

This was tested with freetube_0.18.0-nightly-2885_amd64.deb

**Comment by scampsi** [comment]
I'm intermittently reproducing the reported behaviour on nightly #2844 and #2885.  The videos in this playlist https://youtube.com/playlist?list=PL37EkmqQJzsjVlYSpzqLVAhATrDdGxmsZ mostly.  Other channels / playlists don't reproduce it.  It was so bad in https://www.youtube.com/watch?v=i3DwBAa1boY that I checked the issues and updated to #2885 which doesn't seem any better.

**Comment by RevAngel7** [comment]
I can confirm the issue on my setup with the video https://www.youtube.com/watch?v=i3DwBAa1boY . All 4 seconds only audio with a still picture from the video, until 7 seconds the audio buffer runs out, circling loading animation, next segment, after 4 seconds only audio, after 7 seconds full underrun. And so on and on.

This was tested with freetube_0.18.0-nightly-2885_amd64.deb

Compared to youtube in a firefox browser, the video buffers nearly 90 seconds instantly, no underruns occur there.

**Comment by PikachuEXE** [comment]
Yup I can confirm the loading is slow for https://www.youtube.com/watch?v=i3DwBAa1boY
DASH only, legacy format works fine

![image](https://user-images.githubusercontent.com/1018543/235169001-4ce0674b-2c65-44ab-ad93-492d45f1abe8.png)

**Comment by Growebis** [comment]
> @Growebis @shaicoleman Are you both using the nightly builds? Tried both playing at 3x speed and videos from that channel on the nightlies, but unfortunately I still can't replicate it.

Yes i was using the nightly builds, the build was v0.18.0-nightly-2772 Beta. It seems to depend on the videos as some of the videos i watched were buffering a lot

**Comment by allusive-dev** [comment]
I have just installed `freetube-git` from the paru AUR on arch linux and haven't changed any settings. 
I am also experiencing constant buffering on even 720p60 quality.
On normal browser youtube i can play 4k60 with no buffering.

**Comment by RevAngel7** [comment]
> ![image](https://user-images.githubusercontent.com/1018543/235169001-4ce0674b-2c65-44ab-ad93-492d45f1abe8.png)

@PikachuEXE @absidue 

Would that window with the information helpful, if users encounter slow buffering/loading videos?
(ONLY) If yes is the answer, can one of you explain how to get that window?

Thank you!

**Comment by PikachuEXE** [comment]
I don't think it's needed from all affected users
That screenshot is showing that the requests to something (properly video segments) is slow causing the issue
However finding out the cause is another thing as we have no idea if it's VPN (I got VPN on always), YT server issue, specific video format issue, request generation (in FT and/or underlying libraries), specific video source issue, etc

I will still need to reproduce with VPN off but I might or might not be able to find a solution

**Comment by RevAngel7** [comment]
Thank you!

**Comment by Gorrrg** [comment]
I am too experiencing this issue from time to time. Comparing the gray segments that indicate buffered video, on the same video at the same time, YouTube's browser player is quicker to buffer, whereas it clearly stalls in FreeTube.

One thing to consider would be YT detecting and deliberately slowing down access via something other than the official web player. I remember youtube-dl/yt-dlp having similiar issues with YT that regularly needs to be fixed.

This means there might be ways around it if it's a bug on YouTube's side or even deliberate.

**Comment by Growebis** [comment]
> 
> One thing to consider would be YT detecting and deliberately slowing down access via something other than the official web player. I remember youtube-dl/yt-dlp having similiar issues with YT that regularly needs to be fixed.
> 


How do we know if its a deliberate change by youtube or youtube is just messing around?

**Comment by RevAngel7** [comment]
> > One thing to consider would be YT detecting and deliberately slowing down access via something other than the official web player. I remember youtube-dl/yt-dlp having similiar issues with YT that regularly needs to be fixed.
> 
> How do we know if its a deliberate change by youtube or youtube is just messing around?

That depends how FreeTube identifies, I think. Google decided on several occations, that other apps than browsers should get limited bandwidth. That is why it is so complicated to have youtube on Kodi, with the creation of an API key etc. Maybe, and I guess it is, that is why FreeTube gets less bandwidth than a browser, because FreeTube is considered (from a google point of view) as bad for business, because it prevents ads from showing up.

How does FreeTube identify to the google backend?

**Comment by RevAngel7** [comment]
Or to be blunt: can FreeTube identify as (firefox) browser? I think one of the devs said, it uses the same API key that any browser uses. But maybe it is the identification of FreeTube that does not match with any browser identification that makes google throttle the connection speed.

**Comment by RevAngel7** [comment]
I just realized, that might be more complicated that it sounds. Checking the information that the firefox addon "Trace" obfuscates, there are a lot of identifying factors a browser normally sends. But on the other hand, YouTube is way faster that FreeTube on my end, and I am using the addon Trace for Firefox - and it caches videos maybe 10 times as fast as FreeTube.

**Comment by RevAngel7** [comment]
I would upload some screenshots of the configuration windows from "Trace" up here, but I think for someone to be interested in these, it is easier to install the addon to your browser yourself and check out the settings, to understand what a browser identifies by and what information can be changed regularly without youtube realizing it is getting random information and therefore throttling the connection speed.

**Comment by PikachuEXE** [comment]
Just tested #3474 and loading seems faster (If you want to test it you need to setup dev environment, might be difficult/time consuming for non dev)
You can subscribe to that PR to know when it's merged (and then download nightly version to test)

**Comment by RevAngel7** [comment]
Great, anticipating a download / build we "normies" can get!

**Comment by PikachuEXE** [comment]
Get one here: https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml
![image](https://user-images.githubusercontent.com/1018543/235564135-4e68bee6-2f80-4828-9dfe-01ed614694d7.png)

**Comment by RevAngel7** [comment]
Thank you @PikachuEXE !

Downloaded and installed it. Will test it later and report back the results here.

Thank you again, at all the contributors here, and have a nice day!

**Comment by RevAngel7** [comment]
I have tested the video buffering a bit more in depth, with time now. Sadly, the pre-buffering seems to run out on 50% of most videos I tested. Not 20% as in the first test. 

That might be a random event, considering I used other videos to test from, but it also could mean that the video start should be delayed until at least 10 seconds are buffered. 

Or it could mean that google has already adjusted to your programming changes to throttle connections.

I will keep you updated if that unwanted behaviour is constant or even getting worse over time.

Any comment on my last post @PikachuEXE and @scampsi ?

**Comment by PikachuEXE** [comment]
I have no idea on video resolution
I mostly work on FT features (non video playing part)

https://github.com/FreeTubeApp/FreeTube/pull/3474 is made by another member
And it depends on https://github.com/LuanRT/YouTube.js
So I have no idea if there is anything can be done/related to **video delivery speed** itself

**Comment by absidue** [comment]
I'll comment regarding the 1440p and higher qualities. YouTube provides the DASH streams in multiple formats, MP4 h264, MP4 AV1 and WebM VP9 (audio in M4A and WebM opus). YouTube only provides h264 streams up to 1080p, they provide AV1 and VP9 streams for all resolutions. The video player we use video.js only supports MP4 DASH, so we can't support playback of the WebM VP9 DASH in FreeTube, that leaves us with the h264 and AV1 streams. While the h264 ones are available for all videos all the time, YouTube doesn't have AV1 formats for all videos and even on the few videos that they do have them, they only occasionally return them in the API response, so we can only use them when they are provided.

What does that mean exactly? By default you are limited to 1080p, if you enable the "Allow AV1" setting in FreeTube it will use the AV1 formats when they are available, so if you are lucky with that setting enabled, you'll sometimes be able to get the higher resolution formats.

If you wondered why we don't just simply switch to a different player, it is something we want to do eventually but it will be a lot of work to do. It's also not one of those changes that you could only half do and then forget about the rest of it.

**Comment by RevAngel7** [comment]
Thank you for that extended explanation (and for ignoring my name mixup, sorry for that) @absidue ! That explains a lot.

**Comment by Joerg123** [comment]
Hmm, i have to correct myselft, today it looks different.
I side to side compared (today) with this video: https://youtu.be/m-LjEJS9UnM
v0.18.0: about 15 seconds of stable buffer during the whole video no buffer underruns
v0.18.0-nightly-2873: 5 seconds playback, 5 seconds paused due to buffering, 5 sec playback, 5 sec paused .....
v0.18.0-nightly-2892: only a few seconds buffer, occasional (every 30 seconds) short buffer underrun.

Thus, there is still a huge differents between the versions. What is going on?
Settigs were Dash Formats, Dash AV1 off. The video was 1080p 60 FPS.

**Comment by RevAngel7** [comment]
> Hmm, i have to correct myselft, today it looks different. I side to side compared (today) with this video: https://youtu.be/m-LjEJS9UnM v0.18.0: about 15 seconds of stable buffer during the whole video no buffer underruns v0.18.0-nightly-2873: 5 seconds playback, 5 seconds paused due to buffering, 5 sec playback, 5 sec paused ..... v0.18.0-nightly-2892: only a few seconds buffer, occasional (every 30 seconds) short buffer underrun.
> 
> Thus, there is still a huge differents between the versions. What is going on? Settigs were Dash Formats, Dash AV1 off. The video was 1080p 60 FPS.

That matches my observations.

**Comment by RevAngel7** [comment]
Today, after an hour of watching videos on FreeTube, the propotion of videos that run with and without buffer underruns are only 50/50. Especially full buffer-underruns, where not just video but video and audio stop and show you a circle, and then the recovery will not work towards a state, where you can watch without buffer-underruns - it will underrun again, after the first segment after the previous buffer ran out. And then afterwards, segment after segment.

Since the patch state of FreeTube is the same, since it got better, my personal guess would be that google realized the change and steered against it (because FreeTube generates far less commercial income from ads and sellable user-data).

Tested on v0.18.0-nightly-2891 Beta .deb x64 linux, DASH, AV1 on (but most of the videos were not AV1, but .264).

**Comment by sleeplessKomodo** [comment]
> Yup I can confirm the loading is slow for https://www.youtube.com/watch?v=i3DwBAa1boY DASH only, legacy format works fine
> 
> ![image](https://user-images.githubusercontent.com/1018543/235169001-4ce0674b-2c65-44ab-ad93-492d45f1abe8.png)

can confirm, legacy mode seems to solve this issue

**Comment by RevAngel7** [comment]
"Legacy" uses codecs with less bandwidth (and therefore has a smaller segment and total video size), could that be what makes the difference to DASH? Or does "legacy" on your client load as fast or nearly as fast as on a browser engine?

**Comment by RevAngel7** [comment]
Update today: It seems that the rate, in which videos are correctly and quickly enough buffered, so they can be played without buffer-underruns is down to 25% in 1080p on DASH format (mostly x.264 / AVC1). For me it looks like my prediction was right about google catching up on the last patch. I will update to the last nightly version and test further and post my findings here.

**Comment by aleksejrs** [comment]
DASH is pretty much unusable for me with v0.18.0-nightly-3004 Beta, 1080p or 720p.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
What API are u using and do you use a VPN?

**Comment by aleksejrs** [comment]
Local API, no VPN or other proxy.

**Comment by RevAngel7** [comment]
I am on v0.18.0-nightly-3011 Beta (Linux x64 .deb) version. The rate where videos buffer from beginning to end is down to 15-20% in my tests (local API, no VPN, no proxy, DASH with AV1 enabled, 1080p pref.)

My guess, again, would be that the change in youtube.js made a working change, and google adapted. 

My user experience is now back to the state where I started this issue report.
Compared with youtube over browser, where not a single buffer issue happened for the videos that got underruns all over the video on freetube (again and again, even waiting does not work on longer videos) I came to a personal conclusion: either mimic a normal browser as close as you can or live with google adapting, making this otherwise great freetube unusable.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@aleksejrs could u provide a few videos where u get this issue all the time. We would like to replicate it.

**Comment by aleksejrs** [comment]
https://youtu.be/m9FgRk_ICBk
https://youtu.be/BpPEoZW5IiY (MPV also buffers and plays in 1080p; YouTube player works flawlessly in 720p and 1080p)
https://youtu.be/D8Gz_uOBtG0 (short video, MPV works flawlessly in 1080p/1920p, and YouTube player in 360p and 1080p).

**Comment by Growebis** [comment]
I find that most of the vidoes of the youtube channel Viralhog (https://www.youtube.com/channel/UC3339WgBDKIcxTfywuSmG8w) seem to always underbuffer, especially the shorts videos, when under a vpn, its even more.

also why is it that with a vpn on, most videos become unwatchable because of the buffer?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I find that most of the vidoes of the youtube channel Viralhog (https://www.youtube.com/channel/UC3339WgBDKIcxTfywuSmG8w) seem to always underbuffer, especially the shorts videos, when under a vpn, its even more.

Cant replicate on the latest nightly build. Videos work fine for me.

> also why is it that with a vpn on, most videos become unwatchable because of the buffer?

I think we cant make the assumption that a VPN here is the bottleneck. I'm using one and don't experience any buffering issues. That being said a VPN is an extra hop in your connection so that could slow things down but that shouldn't be noticeable.

**Comment by aleksejrs** [comment]
> a VPN is an extra hop in your connection so that could slow things down but that shouldn't be noticeable.

I heard some ISPs had Google's cache servers installed, so it can be significant, if your VPN is much slower than your normal connection.

**Comment by sleeplessKomodo** [comment]
Using no VPN, with the Local API, and the Dash video format, I experience buffering issues, inconsistently I might add. At times, there are no issues, but ever other video loaded seems to be affected by this buffering issue. I should add, playing videos via firefox on youtube directly operates without issue, as well as watching videos on [Plasmatube ](https://invent.kde.org/multimedia/plasmatube) which uses the invidious API AFAIK.

**Comment by absidue** [comment]
@sleeplessKomodo are you using a nightly build or 0.18.0?

**Comment by RevAngel7** [comment]
I can confirm @sleeplessKomodo 's observation, the same behaviour with a levelled success rate of 33% for good buffering.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I would like to encourage everyone to comment more with URL's of videos that have consistent buffer issues.

We would really like to replicate this behavior.

**Comment by sleeplessKomodo** [comment]
> @sleeplessKomodo are you using a nightly build or 0.18.0?

0.18.0 beta

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@sleeplessKomodo please try the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds) and come back to us if that solves anything for u

**Comment by RevAngel7** [comment]
> I would like to encourage everyone to comment more with URL's of videos that have consistent buffer issues on the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).
> 
> We would really like to replicate this behavior.

Yes, sorry for not doing that. I will try to do better in the future.

**Comment by aleksejrs** [comment]
I've found the reason! In my shorewall, I only allowed "HTTPS" for the user where FreeTube is running, but it needs to connect to 443 using UDP.

**Comment by absidue** [comment]
HTTP 3/QUIC uses UDP, so if you block UDP FreeTube can only use older HTTP versions.

There are probably also added delays because YouTube's servers and FreeTube realise that both support HTTP 3 and then try to use it, but then it fails and has to fall back to the older HTTP versions. Presumably as the blockage is at the network level FreeTube and the server keep trying it, because both of them agree that it should theoretically work.

**Comment by aleksejrs** [comment]
I haven't tested it enough. I am not sure the effect on the playback was real.

**Comment by Joerg123** [comment]
> I've found the reason. I allowed FreeTube to connect to the **TCP** port 443, but for DASH, it needs to connect to port 443 using **UDP** (QUIC, HTTP/3).

I cannot confirm, that this is the problem we are talking about. I downloaded the newest nightly (v0.18.0-nightly-3027) and checked my firewall rules, all protocols are allowed, anyway, v0.18.0 is much faster as the nightly. How much faster depends, but i'm not sure on what it depends. I don't think there are special videos, where the buffer speed is always bad. I also determined like you that sometimes a video is loading especially slow, but is this always the case for this video, or is it just at that particular moment, that this video is buffering slowly? What i can tell for sure is, that the latest (since this thread was opened) nightlys are always slower in buffering and/or rebuffering when fast-forwarding, this is not depending on the kind of video.

Could it perhapps also be something with the network provider? I'm connected with Telekom in south germany with 100 MBit DSL (MagentaZuhause L)

**Comment by Joerg123** [comment]
> @Joerg123 Have you configured a proxy in FreeTube? If yes, it being slow is a known issue, #3405.

No i don't have configured a proxy.
![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28968138/cae0a995-622b-4c80-8928-fdf438eaed02)
![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28968138/acb03f33-ca47-452c-af23-255ae5e2e5d8)
![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28968138/0a0078af-2724-4f47-9658-80e983ae1a9c)
(v0.18.0)

![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28968138/d6b3ebc4-b0d7-492b-ad47-724504ecd4ba)
![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28968138/f4a93555-833d-4974-ac45-d996c573c190)
(v0.18.0-nightly-3027)

I forgot to ask: Why should Google limit the speed for some videos but not for others? What should be the reason behind this measure?

**Comment by RevAngel7** [comment]
> Could it perhapps also be something with the network provider? I'm connected with Telekom in south germany with 100 MBit DSL (MagentaZuhause L)
Probably not. I am on a different provider north bavaria region.
> I forgot to ask: Why should Google limit the speed for some videos but not for others? What should be the reason behind this measure?
Compared to a browser directly on the youtube site, every video is buffering slow. At least that is the case on my side. Since some videos were not really playable with freetube, I switched to browser youtube and had zero issues there (apart from giving google data).

**Comment by RevAngel7** [comment]
Weirdly on installing version v0.18.0-nightly-3027 Beta (x64 .deb) and testing, not a single video had underrun issues. Even clicking on unbuffered parts of longer videos just loaded very fast and did not underrun afterwards. What changed (between nightly-3011 and nightly-3027 considering this issue)?

**Comment by absidue** [comment]
@RevAngel7 Considering you have had playback issues even when they were fixed for most other people, so it's very unlikely that your is in FreeTube itself but something else on your system or setup or how you use FreeTube.

e.g. do you have some weird usage patterns like having loads of video streams playing at once (might make YouTube ratelimit you) or leave FreeTube open for days or weeks on end?

**Comment by scampsi** [comment]
- using freetube-0.18.0-nightly-2892-setup-x64.exe.zip with local API
- in FreeTube some1080p 60fps videos have frequent video freezes while audio continues playing with occasional full freezes of audio & video with spinning circle.  only ever see a very small grey area ahead of current playback position
- in Firefox 1080p 60fps videos never freeze.  always have a large grey area ahead of current playback position

tested this with and without my VPN and same behaviour

I do tend to keep FreeTube open for days or weeks on end.  4 instances of the app but only 1 playing at a time.  I'll start restarting it and report if that makes a difference.

This behaviour is most observable on this playlist:
https://www.youtube.com/watch?v=BtKaoDmbSEI&list=PL37EkmqQJzsjVlYSpzqLVAhATrDdGxmsZ

But I do see it occasionally when other videos in my subscriptions have 1080p 60fps as an option.

**Comment by absidue** [comment]
@scampsi do you have the Allow AV1 option enabled or disabled?

The reason leaving FreeTube open forever could be an issue, is that Electron only clears it's disk caches when it's restarted, so that's probably causing extra slow downs.

Additionally please try the latest nightly to see if that makes a difference like it did for @RevAngel7 .

**Comment by scampsi** [comment]
@absidue Allow AV1 option is disabled

will restart my my machine and install the latest nightly and report back

**Comment by scampsi** [comment]
@absidue now on freetube-0.18.0-nightly-3027-setup-x64.exe.zip

sample size == 1 video from the above playlist.  my main subs feed is open in 1 app instance and the playlist is playing in a 2nd app instance.  both freshly opened on a just rebooted machine.

same observations.

I think the freezes I described are now more frequent - i.e. on a 1080p 60fps video I now get shorter periods of uninterrupted playback before seeing a freeze

I'll test some 1080p non-60fps and 720p 60fps to confirm if they still play without freezing

**Comment by sleeplessKomodo** [comment]
> 

Using a nightly build, and the buffering issues seem to be gone compared to 0.18.0 beta.

**Comment by Joerg123** [comment]
> Compared to a browser directly on the youtube site, every video is buffering slow. At least that is the case on my side.

I totally agree.

I wan't to add: I'm using the portable version (win x64).

**Comment by RevAngel7** [comment]
> @RevAngel7 Considering you have had playback issues even when they were fixed for most other people, so it's very unlikely that your is in FreeTube itself but something else on your system or setup or how you use FreeTube.
> 
> e.g. do you have some weird usage patterns like having loads of video streams playing at once (might make YouTube ratelimit you) or leave FreeTube open for days or weeks on end?

None of that, no. Sorry.

**Comment by RevAngel7** [comment]
I really don't know how I could help you gals/undef/guys there. It was maybe a fluke. Or the choices of my videos. Right now I tested 3 videos - 2 buffered fine (even with one going close to the buffering border), and one failed again, closely after 1:36 minutes of playback... and then again...
It's this video, btw.: https://youtu.be/TJ1eMalJGyg
I am sorry if I given you hope too soon. My time for testing, cross-testing on youtube with a browser and documenting this is getting thinner, I am sorry. But what I found out about a similarity between freetube and the youtube-on-browser test is the buffering of the "first" section of the video.

Youtube (on firefox) buffers exactly to that amount of time, when I press "play" (within seconds btw. No network congestion here). Difference to freetube is, that youtube-browser buffers more than a minute ahead, all the time. As an example, on 1:00 on browser, the video is buffered until 2:15 and so on. Freetube obviously did not or could not do that, since it ran into a buffer-underrun on 1:36 of this video. Youtube-browser could, and buffered on 1:36 the video up to 2:56 (pressing pause at that time and looking for the end of the grey buffer bar).
So, just as my "maybe", freetube has hickups on some videos to find the "next" video segment after the initial buffer was already done, and so ran into a underrun (8 seconds circle animation, then buffer underruns every 5 to 6 seconds of the video until the end of the video).

My firewall reported near zero traffic on the side, while the video was playing btw.

Can you please do the same comparison I just did? Run https://www.youtube.com/watch?v=TJ1eMalJGyg on freetube and then on browser-youtube to compare the if's and when's?

I don't know why it ran so flawlessly yesterday. Maybe we find out the similarity of the videos that get stuck or we find the difference in handling from freetube to youtube-browser to get closer to a solution.

That's it from me for today, have a nice evening!

**Comment by Joerg123** [comment]
> Can you please do the same comparison I just did? Run https://www.youtube.com/watch?v=TJ1eMalJGyg on freetube and then on browser-youtube to compare the if's and when's?

I tested it:
Firefox: fast
Freetube v0.18.0: similar fast, even fast-forwarding was possible without buffer underruns, when waiting 1 second between it.
FreeTube v0.18.0-nightly-3027: Video start already took some seconds, video buffer only a few seconds, fast-forwarding directly leads to buffer-underrun.
![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28968138/2c352721-8baa-45bd-8738-28aec5d7e39c)
v0.18.0-nightly-3027

![grafik](https://github.com/FreeTubeApp/FreeTube/assets/28968138/2fbb69b1-c163-480f-b604-0b5e56d84e96)
v0.18.0

Both screenshoot where taken ~3 seconds after fast-forwarding into an unbufferend part of the video by hopping with the progress bar. I don't know if the statistics are really trustworthy, often i see a acceptable bandwith but buffer underrunds still occour. Today, in this case, it lookls like the statistics talking truth.

In my opinion, not a special video is a problem, but there are just times, where buffering is better and times where it is worse.

The only real constant i can observe, is, that the current nightlys are much worse in video starting, buffering, fast-forwarding, than v0.18.0.

**Comment by scampsi** [comment]
Now using freetube-0.18.0-nightly-3064-setup-x64.exe.

Is there any way to see any debug info as I try to play videos?

The buffering on local dash format has got even worse the last few days.  Most videos can't maintain playback in dash format 480p or above.  Legacy format 720p and Firefox have no issues.

I've seen this consistently over several days with nightly 3027 and 3064.  >50 videos from various channels.  VPN disabled or enabled and connected to various servers in 2 cities.  AV1 enabled and disabled.  Restarting FreeTube frequently.  Win 10 64 bit fully updated.  No heavy CPU, disk IO or network and lots of available RAM.

One thing I've noticed is that if I restart FreeTube after each unsuccesful video playback attempt, there's maybe a 10%-20% chance that the video I wanted to watch will buffer normally.  I can then switch from auto to 1080p with no issues.
Sometimes normal buffering will continue when I watch another video.  Sometimes it's back to buffering unless I close the app and do multiple restarts until the new video also buffers normally.

**Comment by Growebis** [comment]
> The buffering on local dash format has got even worse the last few days. Most videos can't maintain playback in dash format 480p or above. Legacy format 720p and Firefox have no issues.
> 
> I've seen this consistently over several days with nightly 3027 and 3064. >50 videos from various channels. VPN disabled or enabled and connected to various servers in 2 cities. AV1 enabled and disabled. Restarting FreeTube frequently. Win 10 64 bit fully updated. No heavy CPU, disk IO or network and lots of available RAM.
> 
> One thing I've noticed is that if I restart FreeTube after each unsuccesful video playback attempt, there's maybe a 10%-20% 

I've also been noticing that too. it feels like every video  i watch is just stuck on buffering and i have to wait like a couple minutes for the video to be watchable only for it to buffer again. I can try throwing random youtube channels that i find buffer the most. Here are some:

https://www.youtube.com/channel/UCbdbgaxLYyqYiSyGT3uDlFg
https://youtube.com/channel/UC7WQH4kpgxXJYHp8r9IAO-Q

**Comment by Gorrrg** [comment]
I have this with every single video now. I only use "Open in YouTube" now. I wish there was an option to make this the default action when clicking on a thumbnail so I don't have to do one right-click, aim at "Open in YouTube" and then a left click.

**Comment by absidue** [comment]
thanks for all of your recent reports, we are aware that youtube has made changes. there is already a pull request open with another temporary workaround (nothing is permanent with youtube frequently breaking things for us).

**Comment by Draluy** [comment]
Hi,

Just wanted to chip in: After using several nightly builds, nothing worked fine. Even with invidious setup, with the latest nightly, the videos just didnt load.

So I went back to the last official release from the freetube website, and everything works fine, with no invidious proxying required. 1080p loads instantly.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi all,

We've just made some changes that makes buffering much faster. Please test for yourself in the latest nightly build.

**Comment by Joerg123** [comment]
Thanks for the update.
I checked the freetube-0.18.0-nightly-3068-win:
It looks like to me the problem is fixed. Buffering of freetube-0.18.0-nightly-3068-win is similar fast as freetube-0.18.0, at least today. I also tested my last nightly again (FreeTube v0.18.0-nightly-3027) and it was slow as always.

Nice!

**Comment by scampsi** [comment]
freetube-0.18.0-nightly-3068-setup-x64.exe seems to have fixed my issues including 1080p 60fps playback

**Comment by kurqshd941** [comment]
> Hi all,
> 
> We've just made some changes that makes buffering much faster. Please test for yourself in the latest nightly build.

Seems to work perfectly for now! Just curious, what was changed to fix it?

**Comment by absidue** [comment]
@kurqshd941 a new throttling bypass

**Comment by Smurflicious** [comment]
I confirmed the issue was still happening before upgrading, installed the freetube-Setup-0.18.0-nightly-3076 and I can confirm the problem for me is fixed.

Excellent work guys.

**Comment by kurqshd941** [comment]
> @kurqshd941 a new throttling bypass

Was it the user-agent being changed?

**Comment by absidue** [comment]
@kurqshd941 no the user agent doesn't make a difference, plus switching to using the android formats with a new magic params value when available (we still use everything else from the web response so that we aren't missing any information). Unfortunately when youtube breaks android stuff, they make it return errors (you get no useful information, not even the video description), for the web stuff it just loads really really slowly when they break it, so we've had to add a bunch of checks to fall back to the web ones, when youtube inevitably breaks that android bypass again. At least when DASH is throttled with the web one you can still use audio only just fine and the legacy formats work sometimes too.

Basically another temporary workaround until YouTube inevitably breaks stuff again because they don't like third party clients.

**Comment by Joerg123** [comment]
> @kurqshd941 no the user agent doesn't make a difference. we switched to using the android formats with a new magic params value when available (we still use everything else from the web response so that we aren't missing any information). Unfortunately when youtube breaks android stuff, they make it return errors (you get no useful information, not even the video description), for the web stuff it just loads really really slowly when they break it, so we've had to add a bunch of checks to fall back to the web ones, when youtube inevitably breaks that android bypass again. At least when DASH is throttled with the web one you can still use audio only just fine and the legacy formats work sometimes too.
> 
> Basically another temporary workaround until YouTube inevitably breaks stuff again because they don't like third party clients.

Thanks for the explanation. But why then is it, that v18.0 still works fine?

Geertings, and thanks again for the effort.

**Comment by RevAngel7** [comment]
Thank you all for your valuable contributions! I was away a couple of days and installed freetube_0.18.0-nightly-3086_amd64.deb and will test it as soon as I got time.

**Comment by RevAngel7** [comment]
Tests 20/20 videos dash 1080p av1 on without buffering issues. At least as of today, 2023-07-05, with the 3086 version you created.

**Comment by RevAngel7** [comment]
As of today (one week later), 2023-07-13, 20/20 videos without buffering issues, also tested today. Seems like google is a bit slower this time (crossing fingers) with countermeasures. Thank you again to everyone involved in the fix for this issue!

**Comment by 6-AND-9** [comment]
I can confirm this issue as well. Just as I thought, G00gle are being a***oles and rate limiting anyone that does not use their site directly without an ad blocker.

Well, it seems time to move to Odysee, Rumble, PeerTube and other platforms. I sure hope you guys have plans to enable support for these platforms, as I had enough of these lowlifes.

**Comment by absidue** [comment]
@6-AND-9 https://docs.freetubeapp.io/faq/#will-you-consider-adding-support-for-services-outside-of-youtube-twitch-soundcloud-peertube-etc

**Comment by 6-AND-9** [comment]
That's unfortunate. Well, as I move away from YT I guess I won't be using FreeTube anymore if that's not changed.

**Comment by RevAngel7** [comment]
Hmm, since July 5th and freetube_0.18.0-nightly-3086_amd64.deb, continuing v0.19.0 Beta I had longer prebuffering / longer (coincidently 6-to-9 seconds)  load times of new video windows, but no issue like described when I opened this issue. Are you sure @6-AND-9 that this issue has returned for you? Mine still runs fine. If the answer is "yes", can you please elaborate with the details, which version of freetube you run, on what OS, with the settings in freetube you watch the videos, like "1080p, 60fps, local API, no proxy, DASH AV1 enabled"? That would be helpful - thank you!
