### ISSUE TITLE
FreeTube doesn't handle its protocol properly

### ISSUE THREAD

**Issue by maricn** [FreeTubeApp/FreeTube#373]
When using https://github.com/FreeTubeApp/freetube-redirect extension or when simply issuing command (on OSX terminal):
```
open 'freetube://https://www.youtube.com/watch?v=whatever'
```
The FreeTube app opens if closed or gets in focus if it's already open, but nothing else happens. Video doesn't load. Since the extension properly passes the URL to the FreeTube app, and since opening the protocol address outside of extension should also pass the URL to the app properly, I conclude the problem is the app doesn't handle received URL.

Originally observed at https://github.com/FreeTubeApp/freetube-redirect/issues/6.
Documentation about protocol handlers in electron: https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-path-args.

**Comment by PrestonN** [comment]
The problem with this is that I simply don't own a Mac to do testing with.  It's something that I'd like to do soon but I need to be in the right place financially before I get one as getting one would be bought solely for FreeTube testing.  This is also why I don't currently provide `.dmg` builds of FreeTube.

This problem doesn't occur on Windows or Linux, so I am unable to reproduce the issue with the hardware that's available to me.  Unfortunately I don't know when I will be able to fix this, but it's something that I'd like to do when I am able to.

**Comment by maricn** [comment]
@PrestonN Thanks for your reply and your effort on the FreeTube in general.
I'm limited with my knowledge and time to contribute, otherwise would look deeper into it.

But knowing this doesn't happen on Linux/Windows and the link/protocol handling works fine there is an indication it might not be related to electron in the trivial way I imagined (misuse of their API).

Anyways, I think it's good to track this issue here, as opposed to `freetube-redirect` because it belongs here.

**Comment by Mech0z** [comment]
I have a similar problem on Win10, if the app is closed, clicking a youtube link in firefox and having the Freetube redirect addon simply opens Freetube, it does not load the specific video, if I then click the link again when the app is open it will play the video correctly

**Comment by stevenfang1997** [comment]
I have the same issue on Manjaro Linux.

**Comment by PrestonN** [comment]
This should be fixed now in the latest dev builds.  Full release should be coming out sometime this week.

**Comment by fabianski7** [comment]
As I understand it this problem happens with the portable or third party versions of freetube, like AUR? 
I keep having the same problem: freetube opens but the video does not load.

I am using the Privacy Redirect extension, as recommended.

Any way to solve this?

**Comment by PrestonN** [comment]
The solution is to use a non-portable version of the app. The AUR could be fixed if the maintainer made some small changes however I am not the maintainer and cannot make the fix. You will need to ask the maintainer to update the AUR package to work with the extension. Since you're likely running Arch, I can suggest the Flatpak version as that one supports the extension. The AUR version as well as the AppImage build is not supported.

**Comment by fabianski7** [comment]
> The AUR could be fixed if the maintainer made some small changes however I am not the maintainer and cannot make the fix

Are you talking about the freetube.desktop file?
I modified the file according to what I found inside the release that is here on github. 
Basically I added this line (as already suggested by other users here)

`MimeType=x-scheme-handler/freetube;`

the browser opens the FreeTube, but the video player does not open

**Comment by sith-on-mars** [comment]
Seems the issue still persists with the extension like Privacy Redirect and Libredirect on Qt environment, but works fine on gtk environment like Gnome.

Could you improve Qt URL handling? Here is the bug reports I had with [the Libredirect developer](https://github.com/libredirect/libredirect/issues/212) and with [the SUSE developer](https://bugzilla.suse.com/show_bug.cgi?id=1199125), which provide some suggestions for the fix. Hope it helps!

**Comment by ssnor** [comment]
> Seems the issue still persists with the extension like Privacy Redirect and Libredirect on Qt environment, but works fine on gtk environment like Gnome.
> 
> Could you improve Qt URL handling? Here is the bug reports I had with [the Libredirect developer](https://github.com/libredirect/libredirect/issues/212) and with [the SUSE developer](https://bugzilla.suse.com/show_bug.cgi?id=1199125), which provide some suggestions for the fix. Hope it helps!

Thank you for making these bug reports.

I also have this issue on openSUSE Tumbleweed KDE.
According to the SUSE developer the problem is that when Qt's QUrl parses the LibRedirect link a colon is lost.

SUSE will not fix this as they consider the URL FreeTube requires to be invalid and it seems like the LibRedirect developer shares this view.

Does anyone know of a possible workaround?

Would it be possible to reopen this issue as the problem persists and none of the other moving parts are willing to handle the problem?

I wish I could help solve it, but sadly I have no programming experience.

**Comment by ChunkyProgrammer** [comment]
In the future, I'd recommend creating a new issue instead of commenting on a closed one, that way the issue is easier to find (the original issue is about the protocol not working for Mac OS while the issue you found is a bit different)

**Comment by ssnor** [comment]
> In the future, I'd recommend creating a new issue instead of commenting on a closed one, that way the issue is easier to find (the original issue is about the protocol not working for Mac OS while the issue you found is a bit different)

I'm sorry, I'm quite new to engaging with free software projects and trying to get the hang of it.
Will try to be more attentive where I comment in the future.

Thank you so much for creating the fix, I will test it as soon as the pull request has been merged.
Your handle often pops up in the commits, I am thankful for you contributions to this program I use every day!
