### ISSUE TITLE
[Feature Request]: Per-Playlist Autoplay Settings?

### ISSUE THREAD

**Issue by Astralika** [FreeTubeApp/FreeTube#4881]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When the bookmarks tab was exclusively favorites/bookmarks, I enjoyed being able to find a single video and click on it, and get just that video. The ability to actually create personal playlists now is very nice!... _but_ now my little Favorites/Bookmarks playlist is a _playlist_, and if I want to just pull up a single video from it, I have to remember, every time, to hit the Pause Playlist button on the playlist control.

When I attempted to fix this by going into the Player Settings to disable autoplay of playlists, rather than that defaulting the Pause Playlist control to on, it turns off playlists' ability to autoplay entirely, forcing me to either manually move to the next video in _any_ playlist, or go back and turn on Autoplay again for playlists.

### Proposed Solution

The primary solution I've thought of is to create a unique setting on user-created playlists like the existing Favorites/Bookmarks playlist to prevent autoplay _for_ that playlist. That way, playlists like the Favorites list can prevent autoplay and act like lists of videos you can pick single pieces from, while at the same time allowing other playlists to act as full playlists.

### Alternatives Considered

A secondary solution, that could be combined with the above or on its own, would be to associate the Autoplay Playlists setting with the existing Pause Playlist control, such that you can manually tell a given playlist to keep playing through. Even if the above control wasn't implemented, this would allow for both playlists-as-selection-of-videos _and_ playlist-as-continuous-set, with a single prompt from the user instead of having to prompt for every video in a playlist.

### Issue Labels

improvement to existing feature, new optional setting

**Comment by toby63** [comment]
See also: https://github.com/PikachuEXE/FreeTube/issues/70

**Comment by deepspaceaxolotl** [comment]
I was going to make a similar issue myself! I like the idea of setting it per playlist, ideally if it remembered it was manually set so that when the global setting changes, the manually-set ones stay (but the ones that weren't set manually don't). So, a button with three options perhaps: global settings, autoplay on and autoplay off?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Based on the previous discussion on this issue in https://github.com/PikachuEXE/FreeTube/issues/70 we decided this can be easily solved by implementing https://github.com/FreeTubeApp/FreeTube/issues/1181 and https://github.com/FreeTubeApp/FreeTube/issues/2295

**Comment by deepspaceaxolotl** [comment]
I don't see how those two would resolve this? If I'm understanding this correctly, you'd have to turn off/turn on autoplay every time you play a playlist that you want to play differently to your default setting/the setting currently active in the session, when the core issue is that some playlists are inherently used differently than others (watch later and favourites vs series, and of course someone might want to play them differently manually but usually prefer a specific setting). It would be far more intuitive to be able to set a playlist such as watch later or favourites to work essentially as bookmarks, rather than needing to remember to turn off autoplay every time, or vice-versa if one usually uses the former but wants to watch a series or listen to a music playlist sometimes.

**Comment by KandiPanda** [comment]
As a workaround, I added FreeTube as an external player (there was no "custom" or "other" option in the dropdown, so I randomly selected one (`mpv` if it matters), and set `Custom External Player Executable` to point at FreeTube's executable). Then when in the Favorites playlist, I click the "open in external player" button on the video that I want to watch, and it opens it in FreeTube without putting the local playlist in the sidebar at all, basically mimicing the previous single-local-playlist behavior.

**Comment by deepspaceaxolotl** [comment]
I've been running into this issue every day now, forgetting to turn off autoplay for my watch later playlist that I don't want to watch in order. Turning off `Autoplay Playlists` in options works, though it seems it can't be overridden as the pause button stops functioning completely, meaning playlists that one *wants* to autoplay now can't be. I still think a per-playlist option for user playlists would result in much less hassle.

**Comment by deepspaceaxolotl** [comment]
Still dealing with this issue; I would expect the Pause on Current Video button to become one that would temporarily turn on autoplay without affecting the global settings, at the very least. When autoplay playlists is off globally, that button is instead completely non-functional.

I would still like to see per-playlist autoplay options for playlists where one wants them to work differently from the rest (something like a switch between "autoplay on", "autoplay off" and "follow global settings") so reopening this issue would be much appreciated, but at the very least fixing this button issue would allow for changing playlist autoplay modes on the fly (currently only possible for those with autoplay playlists set to on).

**Comment by deepspaceaxolotl** [comment]
Seems the issue I had was fixed at some point, which is welcome!

I would still like to request that this issue be opened, though, as being able to set a preference on a per-playlist basis would be a great improvement (e.g. autoplay on only for a music playlist, or autoplay on globally but off for a watch later playlist).

**Comment by deepspaceaxolotl** [comment]
What is the procedure for reopening an issue? Would very much prefer to just have this reopened rather than opening a new issue that's identical. (See [my comment above](https://github.com/FreeTubeApp/FreeTube/issues/4881#issuecomment-2109731132) for why the proposed solution doesn't make this suggestion obsolete).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@deepspaceaxolotl first of all we do not appreciate the continuous spam of comments on multiple closed issues just to get our attention.

Issues get reopened on a case by case basis. 
The sentiment within the team is still the same on this topic.
