### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#733]
Important note
Please check other open and closed issues for a similar bug before reporting a new one.
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

Behavior of the program
When i'm trying to open a video, i have nothing but this error message.
Expected behavior
The actual page of the video

To Reproduce
Please add all steps to reproduce the behavior:

    Open any video

Desktop (please complete the following information):

    OS: Debian
    OS Version: 10.6
    FreeTube version: 0.9.1

**Comment by Synkky** [comment]
Can you go to the Actions tab (top of the page) and download a portable version of the latest build, in order to confirm that the problem still exists with the latest changes?

**Mini guide (ignore if you already know)**
After selecting a result, there should be an `Artifacts` subsection
If there are no artifacts, go back and choose the next result and so on
You should choose one of the following links:
- freetube_0.9.1_linux_portable_x64
- freetube_0.9.1_amd64.AppImage (if you prefer an AppImage type)

**Comment by EsmailELBoBDev2** [comment]
i just started to get same bug

Im Debian 10 user with latest freetube app

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Same here

Im on windows 10 build 1909
using the latest version of Freetube

**Comment by Asherathe** [comment]
I'm on Peppermint 10, and using the Flatpak version 0.9.1 beta, and getting this intermittently while searching either for channel name or by URL. It doesn't affect every search, but seems random. Sometimes restarting allows the same search to be completed successfully.

**Comment by polarisfm** [comment]
Running Debian 10. This issue occurs on both Debian 10 arm64 and amd64 (using the official .deb package).

**Comment by samuel-lucas6** [comment]
Also getting this error using the .deb package on Pop! OS.

**Comment by GilgusMaximus** [comment]
@everyone
As @Synkky suggested, this is fixed in the newest builds on the Github Action tab.

@Asherathe we are not maintaining the Flatpak version. If an error occurs there, we are unable to help you because our updates get published by the maintainer of the Flatpak version. And if he/she is not up to date with the Nightly Releases, there's nothing we can do for you.

I am closing this right now, because with the newest Nightly build this error is fixed for what I have seen.
If it occurs again, and you did not download one of the Github Action build that were released since commit 46c271aa2261d1da74cf6a71ca779abdf8f0bd05, please do so. If it still persists afterwards, The issue will be reopened

**Comment by bernd972** [comment]
well, thanks for instaclosing the topic >:-(

Where does one get the "Nightly build" and how does one use it?

I only got the normal version for windowsx64 from the normal freetube page, I have no idea about all this overcomplicated github stuff.

**Comment by PrestonN** [comment]
Instructions for the nightly builds are in the [README](https://github.com/FreeTubeApp/FreeTube#automated-builds-nightly--weekly).

May as well post this here as well.  New release will be out very soon.  Waiting for the search patch to get finished and then I'll release shortly afterwards.

**Comment by EsmailELBoBDev2** [comment]
*ahem* i don't know if its my bad luck or what. i did what you said and i used the "Beta" version from github actions tab (literally last action) and i still get the error

**Comment by bernd972** [comment]
I did it that way and it worked, videos are FINALLY getting loaded in an acceptable time and almost no api error anymore. :-)

**Comment by EsmailELBoBDev2** [comment]
okay so its my luck i think. just little question in about tab it says beta or no? because it says beta in my build (which means im using the nightly version right?) so why it does not work with me ? xd

**Comment by bernd972** [comment]
How I went about it:
Clicked te above "Readme" link.
on there, clicked on the "Github actions" link.
then clicked on the first thing " Translated using Weblate (Turkish) Currently translated at 100.0% (415 of 415 strings) Translation: FreeTube/Translations Translate-URL: https://hosted.weblate.org/projects/free-tube/translations... Build #258: Commit 0e74532 pushed by weblate "
(just the first thing with a green checkmark before it, which happens to be the first thing in the list anyways)
then on the next site, I clicked on the "freetube-0.9.1-setup-x64.exe".

which should download you a .zip file.
open it, like you would any zip.
double click the .exe inside.

I did 2 things before clicking the .exe:
1. exporting my subscriptions and history from freetube (is under settings, at the very bottom, there's a row of buttons. one is export history and one is export subscriptions. I chose freetube .db  for both.

2.closing any open freetube window

then, as mentioned, double clicked the .exe from the zip file above, just clicked next everywhere in the following windows, waited for it to be finished.

now opened freetube again, everything worked now.
in the about page, it still says 0.9.1 beta, which is the same as before as I had used the newest version already.
so it doesnt give you any hint if the new night build thing was properly installed or if you are using it,

I jsut felt the difference when suddenly I click a link and after like 2-3 seconds, the video properly load,s almost no api error anymore, as it should have always been!

So yeah, might wanna try the above steps again.
if that doesnt help, then the issue might be elsewhere. you might also wanna check if the shown aerror changes.

lso, I never deinstalled the old freetube version before isntalling the new one.
might be worth a try in your case, first deisntall freetube and then instlal the new version.
just make sure to backup your history and subscriptions beforehand :-)

**Comment by EsmailELBoBDev2** [comment]
Alright, i re downloaded it (but im sure i already did it right) and i tested 3 videos and everything works fine. but still i would not tell my last answer until try for some days :P also i dont notice the fast in opening the videos xD (maybe its my net)

**Comment by Abdulee** [comment]
How do you fix this???

**Comment by PrestonN** [comment]
v0.9.2 should be released now which should fix this issue.  Let me know if you experience the issue again.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
For me the error still occurs in 0.9.2.

Win 10 Home
1909

**Comment by EsmailELBoBDev2** [comment]
It happens with me too but more when i search on something or load comments

**Comment by MetalNeo** [comment]
I believe that I may be running into this issue on nightly 310 of the portable version. The video page loads, but the player loads the video endlessly. This is not happening consistently, only occasionally. This is a screenshot of the last block of errors with logs attached.

![error](https://user-images.githubusercontent.com/53447663/99880810-98854580-2c0d-11eb-89fb-0286281d4aa4.png)

[-1605972100449.log](https://github.com/FreeTubeApp/FreeTube/files/5577856/-1605972100449.log)
[-1605972116511.log](https://github.com/FreeTubeApp/FreeTube/files/5577857/-1605972116511.log)
[-1605972123819.log](https://github.com/FreeTubeApp/FreeTube/files/5577858/-1605972123819.log)
[-1605972156158.log](https://github.com/FreeTubeApp/FreeTube/files/5577860/-1605972156158.log)
[-1605972172196.log](https://github.com/FreeTubeApp/FreeTube/files/5577861/-1605972172196.log)
[-1605972178640.log](https://github.com/FreeTubeApp/FreeTube/files/5577862/-1605972178640.log)
[-1605972183752.log](https://github.com/FreeTubeApp/FreeTube/files/5577864/-1605972183752.log)
[-1605972189223.log](https://github.com/FreeTubeApp/FreeTube/files/5577865/-1605972189223.log)
[-1605972193675.log](https://github.com/FreeTubeApp/FreeTube/files/5577866/-1605972193675.log)
