### ISSUE TITLE
[Complete][Bug]: "Open in <external_player>" does not mark as watched if "Save watched Progress" is off

### ISSUE THREAD

**Issue by Kagukara** [FreeTubeApp/FreeTube#8351]
### EDIT: Was fixed in commit:https://github.com/FreeTubeApp/FreeTube/commit/3d5dae511b93a2c629b0bf0a6085e8f0129ce397. Will be available in `v0.24.0 Beta` when it releases, or you can download the latest [nightly build](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml).

---

### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [x] I have [searched the issue tracker for open and closed issues](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+sort%3Arelevance-desc) that are similar to the bug report I want to file, without success.
- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [x] This issue contains only one bug.
- [x] I have read and agree to follow the [rules](https://docs.freetubeapp.io/community/rules/).

### Describe the bug

When you have "Remember Watch History" on but "Save Watched Progress" is off, clicking "Open in <external_player>" does not mark the video as watched.

**Steps to reproduce:**
1. Backup/Rename existing data, so a new one can be generated.
   - [Linux] `~/.config/FreeTube`
   - [Flatpak] `~/Library/Application Support/FreeTube`
   - [Mac] `~/Library/Application Support/FreeTube`
   - [Windows] `%APPDATA%/FreeTube`
2. Run/Restart FreeTube, then setup an external player in the settings.
3. Still in the settings, turn off "Save Watched Progress" in "Privacy".
4. On a videos thumbnail click "Open in <external_player>" in the bottom left corner.
5. Does not mark as watched.

Turning on "Save Watched Progress" will make mark as watch work for "Open in <external_player>".

### Expected Behavior

I expect "Remember Watch History" to mark as watched when clicking "Open in <external_player>". As you're clicking to watch a video and would like it to **remember** you watched/watching said video.

"Save Watched Progress" should only show the user how far in the video they've gotten (red bar), not marking it as watched. You're saving your **progress** of a video.

### Issue Labels

usability issue

### FreeTube Version

v0.23.12 Beta

### Operating System Version

`Linux destrarch 6.17.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:16 +0000 x86_64 GNU/Linux`

### Installation Method

.AppImage

### Primary API used

Local API

### Additional Information

This doesn't happen with the latest nightly build (`v0.23.12-nightly-6727 Beta`). Didn't see an issues on this but I'm glad it has been fixed with the nightly build.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If its been fixed in the nightly then it will be available in v0.24.0

**Comment by Kagukara** [comment]
This should probably be left open till `v0.24.0` is released or closed as complete (wait for `v0.24.0`), as to not mislead others into thinking this bug is not planned to be fixed.

**Comment by Kagukara** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 

I checked as far back as `v0.23.9-nightly-6480 Beta` (and a few in between) none of them has this issue. Checking the [official releases](https://github.com/FreeTubeApp/FreeTube/releases) `0.23.11`, `0.23.10` and `0.23.09`, they still have this issue. Even though this was fixed as far back or even further back than `v0.23.9-nightly-6480 Beta`.

Why hasn't this been added to any of the official releases yet? With the way the releases are put out at the moment `v0.24.0` seems very far away. Specially since the [roadmap](https://github.com/orgs/FreeTubeApp/projects/5) hasn't been updated since Jul 11, 2024.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
0.23.x releases only contain hotfixes. This isnt something that belongs in a hotfix. 

Please just check commit history of the available branches

> With the way the releases are put out at the moment v0.24.0 seems very far away.

Its not. Please stop making uneducated speculations.
